name: build

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # TODO(cblichmann): Test and add Windows
        os: [ubuntu-20.04, macos-11.0]
        go: [1.13, 1.15.6]
        #include:
        ## First Go version with support for Universal2
        #- os: macos-11.0
        #  go: 1.16

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: '${{ matrix.go }}'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Test
      run: make test
