name: build

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # TODO(cblichmann): Test and add Windows
        os: [ubuntu-20.04, macos-11.0]
        go: [1.13, 1.15.6]
        include:
        - os: macos-12
          go: 1.17.13

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: '${{ matrix.go }}'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Test
      run: make test
